# INSTRUCTIONS

Read the instructions metioned below carefully before attempting the assignment:

    - This assignment has 12 questions and all the questions are mandatory.
    - Read the desciption of the dataset mentioned below carefully.
    - Each question has been commented and written in an independent cell.
    - Write your code in the cell just below the question (Refer Ques-1 - It has been solved for you to understand)
    - Try to submit the assignment within the deadline.
    - Plagiarism will have a huge penality.
    - After completing the assignment upload this notebook to your github and submit the assignment on Google Classroom.
    
    
##### Download the Dataset file(.csv) from here:

https://drive.google.com/file/d/146KzhkfeuzDigbOjaZ1nkTpAHzp7TATz/view?usp=sharing


# COVID19 India dataset

### Description

Title of dataset: covid19india.csv

Sources:

    * A crowdsourced initiative - covid19india.org
    * Date received - 19/07/2020 
    
Number of Instances/Rows

    * Total Number of Rows = 381

Number of Attributes/Fearures/Columns

    * 2 Object, 39 Numerical attributes. 

Attribute Information/Fearures/Columns

    * date: Object Type
    * Status: Confirmed, Recovered, Deceased
    * Below mentioned are remaining 38 columns representing States and UT of India
    
    State 
    Maharashtra, Tamil Nadu, Delhi, Gujarat, Karnataka, Uttar Pradesh, Telangana, Andhra Pradesh, West Bengal, Rajasthan, Haryana, Bihar, Madhya Pradesh, Assam, Odisha, Jammu and Kashmir, Punjab, Kerala, Chhattisgarh, Jharkhand, Uttarakhand, Goa, State Unassigned, Tripura, Manipur, Puducherry, Himachal Pradesh, Ladakh, Nagaland, Chandigarh, Dadra and Nagar Haveli and Daman and Diu, Arunachal Pradesh, Meghalaya, Mizoram, Andaman and Nicobar Islands, Sikkim, Lakshadweep                       
    
    State_code
    MH, TN, DL, GJ, KA, UP, TG, AP, WB, RJ, HR, BR, MP, AS, OR, JK, PB, KL, CT, JH, UT, GA, UN, TR, MN, PY, HP, LA, NL, CH, DN, AR, ML, MZ, AN, SK, LD

In [1]:
# Q1 - Import the required Library (Sample question and answer)

import numpy as np
import pandas as pd

In [2]:
# Q2 - Read the csv file to the pandas dataframe

data = pd.read_csv("covid19india.csv")

In [14]:
# Q3 - Display the top 5 rows of the dataframe

print(data.head())

        date     status  an  ap  ar  as  br  ch  ct  dd  ...  py  rj  sk  tg  \
0  14-Mar-20  Confirmed   0   1   0   0   0   0   0   0  ...   0   3   0   1
1  14-Mar-20  Recovered   0   0   0   0   0   0   0   0  ...   0   1   0   0
2  14-Mar-20   Deceased   0   0   0   0   0   0   0   0  ...   0   0   0   0
3  15-Mar-20  Confirmed   0   0   0   0   0   0   0   0  ...   0   1   0   2
4  15-Mar-20  Recovered   0   0   0   0   0   0   0   0  ...   0   2   0   1

   tn  tr  un  up  ut  wb
0   1   0   0  12   0   0
1   0   0   0   4   0   0
2   0   0   0   0   0   0
3   0   0   0   1   0   0
4   0   0   0   0   0   0

[5 rows x 40 columns]

In [15]:
# Q4 - Display the bottom 5 rows of the dataframe

print(data.tail())

          date     status  an    ap  ar    as    br  ch   ct  dd  ...  py  \
376  17-Jul-20  Recovered   0   905  22   551   896   4   61   0  ...  67
377  17-Jul-20   Deceased   0    42   0     1     6   0    3   0  ...   3
378  18-Jul-20  Confirmed   0  3963  41  1117  1667  31  243   0  ...  58
379  18-Jul-20  Recovered   0  1465  99  1060   774   5  146   0  ...  48
380  18-Jul-20   Deceased   0    52   0     2     4   1    0   0  ...   3

      rj  sk    tg    tn   tr   un    up   ut    wb
376  656   1  1410  3391   47    0   959   26   838
377    8   0     7    79    0    0    38    1    26
378  711  19  1284  4807  171 -368  1873  174  2198
379  518   2  1902  3049   51    0  1030   60  1286
380    7   0     6    88    2    0    24    1    27

[5 rows x 40 columns]

In [6]:
# Q5 - How many columns and rows are there in the dataframe?

shape = data.shape
print("Rows:",shape[0],"\nColumns:",shape[1])

Rows: 381
Columns: 40

In [23]:
# Q6 - Display a breif overview of all the columns data type and missing values?

print("Data Types")
print(data.dtypes)
print("\nMissing Values")
print(data[data.isnull().any(axis=1)])

# Empty df is returned when looking up missing values. This implies that there are no missing values in this dataset.

Data Types
date      object
status    object
an         int64
ap         int64
ar         int64
as         int64
br         int64
ch         int64
ct         int64
dd         int64
dl         int64
dn         int64
ga         int64
gj         int64
hp         int64
hr         int64
jh         int64
jk         int64
ka         int64
kl         int64
la         int64
ld         int64
mh         int64
ml         int64
mn         int64
mp         int64
mz         int64
nl         int64
or         int64
pb         int64
py         int64
rj         int64
sk         int64
tg         int64
tn         int64
tr         int64
un         int64
up         int64
ut         int64
wb         int64
dtype: object

Missing Values
Empty DataFrame
Columns: [date, status, an, ap, ar, as, br, ch, ct, dd, dl, dn, ga, gj, hp, hr, jh, jk, ka, kl, la, ld, mh, ml, mn, mp, mz, nl, or, pb, py, rj, sk, tg, tn, tr, un, up, ut, wb]
Index: []

[0 rows x 40 columns]

In [25]:
# Q7 - Display the descriptive statistical analysis on numerical columns of the dataframe?

print(data.describe())

               an           ap          ar           as           br  \
count  381.000000   381.000000  381.000000   381.000000   381.000000
mean     0.821522   175.742782    2.433071   100.007874   107.388451
std      2.422408   436.279518    9.113256   219.505910   235.197288
min      0.000000     0.000000    0.000000    -1.000000     0.000000
25%      0.000000     1.000000    0.000000     0.000000     0.000000
50%      0.000000    25.000000    0.000000     0.000000     5.000000
75%      0.000000    97.000000    0.000000    79.000000   146.000000
max     20.000000  3963.000000   99.000000  1218.000000  1742.000000

              ch          ct     dd           dl          dn  ...          py  \
count  381.00000  381.000000  381.0   381.000000  381.000000  ...  381.000000
mean     3.11811   23.433071    0.0   594.364829    2.868766  ...    7.826772
std      7.27101   44.647613    0.0  1027.573886    7.553918  ...   18.879296
min      0.00000    0.000000    0.0     0.000000    0.000000  ...    0.000000
25%      0.00000    0.000000    0.0     4.000000    0.000000  ...    0.000000
50%      0.00000    0.000000    0.0    67.000000    0.000000  ...    0.000000
75%      4.00000   28.000000    0.0   504.000000    0.000000  ...    4.000000
max     79.00000  249.000000    0.0  7725.000000   50.000000  ...  147.000000

               rj          sk           tg           tn          tr  \
count  381.000000  381.000000   381.000000   381.000000  381.000000
mean   131.750656    0.989501   196.314961   740.086614   11.569554
std    169.953688    4.626570   443.763249  1263.481723   26.517988
min      0.000000   -1.000000     0.000000     0.000000   -2.000000
25%      4.000000    0.000000     2.000000     3.000000    0.000000
50%     42.000000    0.000000    10.000000    63.000000    0.000000
75%    236.000000    0.000000    72.000000   817.000000    8.000000
max    866.000000   50.000000  2078.000000  5106.000000  171.000000

                un           up          ut           wb
count   381.000000   381.000000  381.000000   381.000000
mean      0.427822   201.595801   19.446194   170.141732
std     204.755665   337.816167   36.746792   314.410201
min   -1295.000000     0.000000    0.000000   -19.000000
25%       0.000000     4.000000    0.000000     3.000000
50%       0.000000    30.000000    1.000000    18.000000
75%       0.000000   260.000000   25.000000   188.000000
max    1043.000000  2058.000000  216.000000  2198.000000

[8 rows x 38 columns]

In [26]:
# Q8 - What were the number of confirmed cases in Rajasthan on 1st July 2020?

print(data.loc[(data['date'] == '01-Jul-20') & (data['status'] == 'Confirmed'), ['date','status','rj']])

          date     status   rj
327  01-Jul-20  Confirmed  304

In [29]:
# Q9 - What is the number of Deceased cases on 18th July 2020?

print("Deceased cases on 18th July 2020:",data.loc[(data['date'] == '18-Jul-20') & (data['status'] == 'Deceased')].sum(axis=1).values[0])

Deceased cases on 18th July 2020: 543

In [10]:
# Q10 - Create a new column 'total'. Values in this column is supposed to contain the sum of corresponding row.

data['total'] = data.sum(axis=1)

In [30]:
# Q11 - Group by on 'Status' column and display first.

data_g = data.groupby('status')
print(data_g.first())

                date  an  ap  ar  as  br  ch  ct  dd  dl  ...  py  rj  sk  tg  \
status                                                    ...
Confirmed  14-Mar-20   0   1   0   0   0   0   0   0   7  ...   0   3   0   1
Deceased   14-Mar-20   0   0   0   0   0   0   0   0   1  ...   0   0   0   0
Recovered  14-Mar-20   0   0   0   0   0   0   0   0   1  ...   0   1   0   0

           tn  tr  un  up  ut  wb
status
Confirmed   1   0   0  12   0   0
Deceased    0   0   0   0   0   0
Recovered   0   0   0   4   0   0

[3 rows x 39 columns]

In [31]:
# Q12 - Display the overall basic statistical analysis of Rajasthan for different status
# (confirmed, recovered and deceased)

print(data_g['rj'].describe())

           count        mean         std  min   25%    50%    75%    max
status
Confirmed  127.0  224.409449  191.507858  0.0  76.5  210.0  304.5  866.0
Deceased   127.0    4.354331    3.680768  0.0   1.0    4.0    7.0   17.0
Recovered  127.0  166.488189  155.543383  0.0  17.0  126.0  276.0  656.0